# build.yml
on:
  pull_request:
    branches:        
    - main            

name: Update main folder in Databricks

jobs:
  update-staging:
    name: Update main
    runs-on: ubuntu-latest
    steps:
      - name: Update repos
        id: updateRepos
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://mlab-masterthesis.cloud.databricks.com/api/2.0/repos/3478964653040535'
          method: 'PATCH'
          bearerToken: ${{ secrets.DATABRICKS_TOKEN }}
          contentType: 'application/json'
          data: '{"branch":"main"}'
      - name: Show Response
        run: echo ${{ steps.updateRepos.outputs.response }}
